apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
type: Opaque
data:
  username: bXktdXNlcm5hbWU=  # "my-username" base64 encoded
  password: bXktcGFzc3dvcmQ=  # "my-password" base64 encoded
