apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-namespace
data:
  index.html: |
    <html>
      <head><title>Hello, World!</title></head>
      <body>
        <h1>Hello, World!</h1>
        <p>Welcome to my Nginx server.</p>
      </body>
    </html>
