apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: my-namespace
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  volumes:
  - name: nginx-html
    configMap:
      name: nginx-config
  restartPolicy: Never
